### ISSUE TITLE
predict two images

### ISSUE THREAD

**Issue by iamheidi** [L1aoXingyu/fast-reid#21]
Hello.
I want to know the similarity of two images.
Your code is the evaluation output.
I want to know the code to predict.
E.g. Given two image inputs
Can you tell if this is the same or not?
Or get each features?

**Comment by L1aoXingyu** [comment]
I will put an example in two or three days.

**Comment by L1aoXingyu** [comment]
see demo.py

**Comment by wduo** [comment]
Hi, Where is demo.py?

**Comment by L1aoXingyu** [comment]
I will add demo.py in this weekends.

**Comment by L1aoXingyu** [comment]
I have added demo.py in demo folder. You can check it.

**Comment by wduo** [comment]
Great! I test it now. Thanks.
