### ISSUE TITLE
TypeError: object of type 'RandomIdentitySampler' has no len()

### ISSUE THREAD

**Issue by DeepAlchemist** [L1aoXingyu/fast-reid#39]

**Comment by L1aoXingyu** [comment]
Could you please show the complete error logging?

**Comment by DeepAlchemist** [comment]
No need to show, when we want to get len(train_data_loader), the error raises because the RandomIdentitySampler does not implement def __len__().

**Comment by L1aoXingyu** [comment]
because in my implementation, the data loader is an infinite loop, so you cannot get the length.

**Comment by L1aoXingyu** [comment]
you can access the dataset length via `len(train_data_loader.dataset)`

**Comment by DeepAlchemist** [comment]
OK, thx.
